[package]
name = "rpguru_sdk"
version = "1.0.0"  # API
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
tonic = { workspace = true }
tonic-prost = { workspace = true }
prost = { workspace = true }

[build-dependencies]
tonic-prost-build = { workspace = true }
