use crate::entities::db::canvas::{CanvasFence, CanvasId, CanvasUiPosition};
use crate::entities::db::dns::DnsProviderId;
use crate::entities::db::fence;
pub use crate::entities::db::pod::{ProxyProtocolVersion, TlsConfig};
use crate::entities::db::port::{
    PortDirection, PortEntity, PortKind, insert_ports, ports_of, reshape_ports,
};
use crate::entities::db::server::ServerId;
use crate::entities::db::tree;
use base::db::{Db, Error};
use db_types::{table_record, text_enum};
use kanau::processor::Processor;
use serde::{Deserialize, Serialize};
use sqlx::PgConnection;
use sqlx::types::Json;

table_record!(NodeId, "orchestration_node");

/// The conflict reported when an import would make a canvas its own ancestor.
pub const IMPORT_CYCLE: &str = "a canvas cannot import itself or an ancestor";
/// The conflict reported when a canvas is imported a second time.
pub const ALREADY_IMPORTED: &str = "canvas is already imported";

#[derive(Debug, Clone)]
pub struct NodeEntity {
    pub id: NodeId,
    pub canvas: CanvasId,
    pub name: String,
    pub comment: String,
    pub spec: NodeSpec,
    pub position: CanvasUiPosition,
    /// Set on a node generated by a universal node's expansion; `None` for every
    /// node an operator drew. See [`Lane`].
    pub lane: Option<Lane>,
}

impl NodeEntity {
    pub fn is_universal(&self) -> bool {
        self.spec.is_universal()
    }
}

/// An `orchestration_node` row as the database hands it out. The lane is six
/// nullable columns that are all set or all unset (a CHECK constraint says so);
/// the entity folds them into an `Option<Lane>`.
#[derive(sqlx::FromRow)]
pub(crate) struct NodeRow {
    id: NodeId,
    canvas: CanvasId,
    name: String,
    comment: String,
    #[sqlx(json)]
    spec: NodeSpec,
    #[sqlx(flatten)]
    position: CanvasUiPosition,
    lane_key: Option<String>,
    lane_group: Option<NodeId>,
    lane_channel: Option<NodeId>,
    lane_role: Option<LaneRole>,
    lane_source: Option<NodeId>,
    lane_via: Option<String>,
}

impl From<NodeRow> for NodeEntity {
    fn from(row: NodeRow) -> Self {
        let lane = match (
            row.lane_key,
            row.lane_group,
            row.lane_channel,
            row.lane_role,
        ) {
            (Some(key), Some(group), Some(channel), Some(role)) => Some(Lane {
                key,
                group,
                channel,
                role,
                source: row.lane_source,
                via: row.lane_via,
            }),
            _ => None,
        };
        NodeEntity {
            id: row.id,
            canvas: row.canvas,
            name: row.name,
            comment: row.comment,
            spec: row.spec,
            position: row.position,
            lane,
        }
    }
}

/// The node with the given id, inside a transaction.
pub(crate) async fn node_by_id(
    conn: &mut PgConnection,
    id: &NodeId,
) -> Result<Option<NodeEntity>, Error> {
    let row: Option<NodeRow> = sqlx::query_as("SELECT * FROM orchestration_node WHERE id = $1")
        .bind(id)
        .fetch_optional(conn)
        .await?;
    Ok(row.map(NodeEntity::from))
}

/// Rewrites a node's spec, keeping the lifted link columns in step with it.
pub(crate) async fn write_spec(
    conn: &mut PgConnection,
    id: &NodeId,
    spec: &NodeSpec,
) -> Result<(), Error> {
    let links = spec.links();
    sqlx::query(
        "UPDATE orchestration_node
         SET spec = $2, import_canvas = $3, pod_server = $4, tls_dns_provider = $5
         WHERE id = $1",
    )
    .bind(id)
    .bind(Json(spec))
    .bind(links.import_canvas)
    .bind(links.pod_server)
    .bind(links.tls_dns_provider)
    .execute(conn)
    .await
    .map_err(|e| {
        Error::from(e).conflict_on("orchestration_node_import_canvas_key", ALREADY_IMPORTED)
    })?;
    Ok(())
}

/// Inserts a node row; `lane` is `None` for a node an operator drew.
#[allow(clippy::too_many_arguments)]
pub(crate) async fn insert_node(
    conn: &mut PgConnection,
    canvas: &CanvasId,
    name: &str,
    comment: &str,
    spec: &NodeSpec,
    position: CanvasUiPosition,
    lane: Option<&Lane>,
) -> Result<NodeEntity, Error> {
    let links = spec.links();
    let row: NodeRow = sqlx::query_as(
        "INSERT INTO orchestration_node
             (id, canvas, name, comment, spec, position_x, position_y,
              import_canvas, pod_server, tls_dns_provider,
              lane_key, lane_group, lane_channel, lane_role, lane_source, lane_via)
         VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16)
         RETURNING *",
    )
    .bind(NodeId::new())
    .bind(canvas)
    .bind(name)
    .bind(comment)
    .bind(Json(spec))
    .bind(position.x)
    .bind(position.y)
    .bind(links.import_canvas)
    .bind(links.pod_server)
    .bind(links.tls_dns_provider)
    .bind(lane.map(|l| l.key.as_str()))
    .bind(lane.map(|l| &l.group))
    .bind(lane.map(|l| &l.channel))
    .bind(lane.map(|l| l.role))
    .bind(lane.and_then(|l| l.source.as_ref()))
    .bind(lane.and_then(|l| l.via.as_deref()))
    .fetch_one(conn)
    .await
    .map_err(|e| {
        Error::from(e).conflict_on("orchestration_node_import_canvas_key", ALREADY_IMPORTED)
    })?;
    Ok(row.into())
}

/// The identity of a generated node within the expansion of a universal node.
///
/// `key` is what the reconciler diffs by:
/// `"{group}:{channel}:{role}:{source or -}"`, all record keys. A lane whose key
/// survives an edit keeps its row, and with it its port ids, its health history
/// and (for a landing pod) its port number.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct Lane {
    pub key: String,
    /// The universal node this lane was generated for.
    pub group: NodeId,
    /// The entry pod whose channel this lane carries.
    pub channel: NodeId,
    pub role: LaneRole,
    /// For a landing pod: the universal node the bundle came from. For a
    /// distributor's relay: the universal pod it dials. `None` otherwise.
    pub source: Option<NodeId>,
    /// The chain of nodes a channel came through before the node that
    /// generated this lane fanned it out again (`a+b+c`, record keys), so a
    /// channel reaching one distribute node from several upstream servers
    /// gets one fan-out per upstream path. `None` where the channel starts.
    pub via: Option<String>,
}

impl Lane {
    pub fn key_for(
        group: &NodeId,
        channel: &NodeId,
        role: LaneRole,
        source: Option<&NodeId>,
        via: Option<&str>,
    ) -> String {
        let mut key = format!(
            "{}:{}:{}:{}",
            group,
            channel,
            role.as_str(),
            source.map(NodeId::as_str).unwrap_or("-")
        );
        if let Some(via) = via {
            key.push(':');
            key.push_str(via);
        }
        key
    }

    pub fn new(
        group: &NodeId,
        channel: &NodeId,
        role: LaneRole,
        source: Option<&NodeId>,
        via: Option<&str>,
    ) -> Self {
        Self {
            key: Self::key_for(group, channel, role, source, via),
            group: group.clone(),
            channel: channel.clone(),
            role,
            source: source.cloned(),
            via: via.map(str::to_string),
        }
    }
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum LaneRole {
    /// The load balancer fanning one channel over a distributor's bundles.
    Distribute,
    /// A relay dialling a landing pod on the far side of a bundle.
    Relay,
    /// A real pod on a universal pod's server, one per channel per incoming bundle.
    Landing,
    /// The load balancer joining several landing pods to one exit path.
    Aggregate,
}
text_enum!(LaneRole {
    Distribute => "distribute",
    Relay => "relay",
    Landing => "landing",
    Aggregate => "aggregate",
});

/// Stored as one `jsonb` document, `{ "type": "<variant>", "config": { ... } }`.
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(tag = "type", content = "config", rename_all = "snake_case")]
pub enum NodeSpec {
    CanvasExport(CanvasExportConfig),
    CanvasImport(CanvasImportConfig),
    Pod(PodConfig),
    Entry(EntryConfig),
    Relay(RelayConfig),
    Exit(ExitConfig),
    LoadBalanceDistribute(LoadBalanceDistributeConfig),
    LoadBalanceAggregate(LoadBalanceAggregateConfig),
    UniversalPod(UniversalPodConfig),
}

impl NodeSpec {
    /// Whether this is a server's universal pod: a node with no traffic path of
    /// its own, whose ports are all bundle ports (see `services::universal`).
    pub fn is_universal(&self) -> bool {
        matches!(self, NodeSpec::UniversalPod(_))
    }

    /// Whether bundles can be drawn on this node: a universal pod, or a
    /// load-balance node, whose on-demand `chan:` / `bundle_*` ports sit next to
    /// its hand-drawn ones.
    pub fn takes_bundles(&self) -> bool {
        matches!(
            self,
            NodeSpec::UniversalPod(_)
                | NodeSpec::LoadBalanceDistribute(_)
                | NodeSpec::LoadBalanceAggregate(_)
        )
    }

    /// The rows this spec links to, lifted out of the document into the
    /// `import_canvas` / `pod_server` / `tls_dns_provider` columns by every node
    /// write, so the database can index and foreign-key them.
    pub fn links(&self) -> SpecLinks<'_> {
        match self {
            NodeSpec::CanvasImport(cfg) => SpecLinks {
                import_canvas: Some(&cfg.canvas),
                ..SpecLinks::default()
            },
            NodeSpec::Pod(cfg) => SpecLinks {
                pod_server: Some(&cfg.server),
                ..SpecLinks::default()
            },
            NodeSpec::UniversalPod(cfg) => SpecLinks {
                pod_server: Some(&cfg.server),
                ..SpecLinks::default()
            },
            NodeSpec::Entry(cfg) => SpecLinks {
                tls_dns_provider: cfg.tls.as_ref().map(|tls| &tls.dns_provider),
                ..SpecLinks::default()
            },
            NodeSpec::CanvasExport(_)
            | NodeSpec::Relay(_)
            | NodeSpec::Exit(_)
            | NodeSpec::LoadBalanceDistribute(_)
            | NodeSpec::LoadBalanceAggregate(_) => SpecLinks::default(),
        }
    }
}

/// The foreign keys a [`NodeSpec`] carries; see [`NodeSpec::links`].
#[derive(Debug, Default, Clone, Copy)]
pub struct SpecLinks<'a> {
    pub import_canvas: Option<&'a CanvasId>,
    pub pod_server: Option<&'a ServerId>,
    pub tls_dns_provider: Option<&'a DnsProviderId>,
}

/// A server's universal pod: created with the server, exactly one per server.
/// Bundles come in on `bundle_in:<source>` ports, every channel they carry lands
/// on a generated pod of this server, and the fixed `bundle_out` hands the
/// bundle on to another universal pod or to a load-balance aggregate node.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UniversalPodConfig {
    pub server: ServerId,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CanvasExportConfig {
    pub kind: PortKind,
    pub direction: CanvasExportAs,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum CanvasExportAs {
    InputIntoCanvas,
    OutputOutOfCanvas,
}

/// An import node embeds another canvas as one node. The target is immutable:
/// re-targeting is "retire and import again". The importing node's ports are
/// derived from the target's export nodes (see
/// [`crate::services::node::import_port_layout`]) and follow every export edit.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CanvasImportConfig {
    pub canvas: CanvasId,
}

/// One listener on one server: a forwarding rule's socket.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PodConfig {
    /// The server this pod listens on; it pins the pod to exactly one server.
    pub server: ServerId,
    pub port: u16,
    /// The address to bind. `None` binds every address of the host (dual-stack
    /// `::`); `0.0.0.0` restricts it to IPv4; a literal pins one interface.
    #[serde(default)]
    pub bind_ip: Option<String>,
    /// The address other servers dial for this pod. `None` means the server's
    /// effective address.
    #[serde(default)]
    pub advertise_ip: Option<String>,
}

impl PodConfig {
    /// The parsed bind address, or the value that failed to parse.
    pub fn bind_ip(&self) -> Result<Option<std::net::IpAddr>, String> {
        parse_optional_ip(&self.bind_ip)
    }

    /// The parsed advertise address, or the value that failed to parse.
    pub fn advertise_ip(&self) -> Result<Option<std::net::IpAddr>, String> {
        parse_optional_ip(&self.advertise_ip)
    }

    /// The socket this pod binds, `[::]` standing for "all addresses".
    pub fn listen_display(&self) -> String {
        match self.bind_ip.as_deref() {
            None => format!("[::]:{}", self.port),
            Some(ip) if ip.contains(':') => format!("[{ip}]:{}", self.port),
            Some(ip) => format!("{ip}:{}", self.port),
        }
    }
}

fn parse_optional_ip(value: &Option<String>) -> Result<Option<std::net::IpAddr>, String> {
    match value.as_deref() {
        None => Ok(None),
        Some(raw) => raw
            .parse::<std::net::IpAddr>()
            .map(Some)
            .map_err(|_| raw.to_string()),
    }
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct EntryConfig {
    pub receive_proxy_protocol: Option<ProxyProtocolVersion>,
    pub tls: Option<TlsConfig>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct RelayConfig {
    pub protocol: RelayProtocol,
    pub override_ip_address: Option<String>,
    pub override_port: Option<u16>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Default, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum RelayProtocol {
    #[default]
    TcpRaw,
    TcpTls,
    Quic,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExitConfig {
    pub destination: String,
    pub pass_proxy_protocol: Option<ProxyProtocolVersion>,
}

/// One member of a load-balance node as the operator declares it. `slot` is the
/// member's stable number: its port is `member_<slot>`, so a rename or a
/// reorder keeps the bundle drawn on it; `name` is what the operator calls it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LoadBalanceMember {
    pub slot: u32,
    pub name: String,
}

impl LoadBalanceMember {
    pub fn port_key(&self) -> String {
        format!("{MEMBER_PREFIX}{}", self.slot)
    }
}

/// The key prefix of a member port; the rest is the member's slot.
pub const MEMBER_PREFIX: &str = "member_";

/// The operator's rule: `members` are the bundles this node splits into, one
/// bundle port each, in the order given. `protocol` is how the channels bundled
/// out are relayed to the universal pods they land on. A lane node (generated by
/// the expansion) has no members here: its ports are thin and counted.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct LoadBalanceDistributeConfig {
    pub mode: LoadBalanceMode,
    #[serde(default)]
    pub protocol: RelayProtocol,
    #[serde(default)]
    pub members: Vec<LoadBalanceMember>,
}

/// `members` are the bundles this node joins, one bundle port each.
#[derive(Debug, Clone, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct LoadBalanceAggregateConfig {
    #[serde(default)]
    pub members: Vec<LoadBalanceMember>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum LoadBalanceMode {
    RoundRobin,
    Random,
    IpHash,
    Fallback,
}

impl From<LoadBalanceMode> for guru_worker_config::LoadBalanceStrategy {
    fn from(value: LoadBalanceMode) -> Self {
        match value {
            LoadBalanceMode::RoundRobin => guru_worker_config::LoadBalanceStrategy::RoundRobin,
            LoadBalanceMode::Random => guru_worker_config::LoadBalanceStrategy::Random,
            LoadBalanceMode::IpHash => guru_worker_config::LoadBalanceStrategy::IpHash,
            LoadBalanceMode::Fallback => guru_worker_config::LoadBalanceStrategy::Fallback,
        }
    }
}

#[derive(Debug, Clone)]
pub struct NodeWithPorts {
    pub node: NodeEntity,
    pub ports: Vec<PortEntity>,
}

/// A port to create together with its node.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct NewPort {
    pub kind: PortKind,
    pub direction: PortDirection,
    pub key: String,
    pub position: i64,
}

/// The importing node whose derived ports must follow this edit, and the port
/// set it must end up with. `None` when the edited node is not an export node
/// of an imported canvas.
///
/// Applied by [`crate::entities::db::port::reshape_ports`] in the same transaction
/// as the export edit: a mirrored port whose key survives keeps its row and edges.
#[derive(Debug, Clone)]
pub struct ImportSync {
    pub node: NodeId,
    pub ports: Vec<NewPort>,
}

/// The key `import_sync.ports` uses for the export node being created, whose id
/// only exists inside the transaction; `CreateNodeRow` substitutes the real one
/// after the insert.
pub const PENDING_EXPORT_KEY: &str = "pending-node";

pub struct CreateNodeRow {
    pub canvas: CanvasId,
    pub name: String,
    pub comment: String,
    pub spec: NodeSpec,
    pub position: CanvasUiPosition,
    pub ports: Vec<NewPort>,
    pub import_sync: Option<ImportSync>,
    /// The importer tree the create was validated against, fencing the write;
    /// `None` bumps unconditionally (a snapshotless create, e.g. a server's
    /// universal pod).
    pub fence: Option<CanvasFence>,
    /// For an import node, the target tree — a second, independent root loaded
    /// and validated alongside the importer — claimed in the same transaction so
    /// a concurrent edit to the target rolls the import back. Only its generation
    /// is used; the target root is the import's `spec.config.canvas`.
    pub target_fence: Option<CanvasFence>,
}

impl Processor<CreateNodeRow> for Db {
    type Output = NodeWithPorts;
    type Error = Error;
    #[tracing::instrument(
        name = "Query-Transaction:CreateNodeRow",
        skip_all,
        err,
        fields(
            canvas = %input.canvas,
            name = ?input.name,
        )
    )]
    async fn process(&self, input: CreateNodeRow) -> Result<Self::Output, Self::Error> {
        let mut tx = self.db().begin().await?;
        if let NodeSpec::CanvasImport(cfg) = &input.spec {
            let mut chain = tree::ancestors_of(&mut tx, &input.canvas).await?;
            chain.push(input.canvas.clone());
            if chain.contains(&cfg.canvas) {
                return Err(Error::Conflict(IMPORT_CYCLE));
            }
            // "Already imported" is the UNIQUE constraint on `import_canvas`,
            // named by `insert_node`.
        }
        let node = insert_node(
            &mut tx,
            &input.canvas,
            &input.name,
            &input.comment,
            &input.spec,
            input.position,
            None,
        )
        .await?;
        let ports = insert_ports(&mut tx, &node.id, &input.ports).await?;
        // The target stops being a root: its own pending derivation collapses
        // into this tree's. Writing its row also makes two concurrent imports of
        // each other contend instead of forming a cycle.
        if let NodeSpec::CanvasImport(cfg) = &input.spec {
            match &input.target_fence {
                None => {
                    sqlx::query(
                        "UPDATE orchestration_canvas SET derived_generation = generation WHERE id = $1",
                    )
                    .bind(&cfg.canvas)
                    .execute(&mut *tx)
                    .await?;
                }
                Some(target) => fence::claim_root(&mut tx, &cfg.canvas, target.generation).await?,
            }
        }
        // An export node's mirrored port on the importer is keyed by the export's
        // id, which only exists now: swap the placeholder for it.
        if let Some(sync) = &input.import_sync {
            let synced: Vec<NewPort> = sync
                .ports
                .iter()
                .map(|p| {
                    if p.key == PENDING_EXPORT_KEY {
                        NewPort {
                            key: node.id.to_string(),
                            ..p.clone()
                        }
                    } else {
                        p.clone()
                    }
                })
                .collect();
            reshape_ports(&mut tx, &sync.node, &synced).await?;
        }
        fence::touch_checked(&mut tx, &input.canvas, input.fence.as_ref()).await?;
        tx.commit().await?;
        Ok(NodeWithPorts { node, ports })
    }
}

#[derive(Debug)]
pub struct FindNodeById {
    pub id: NodeId,
}

impl Processor<FindNodeById> for Db {
    type Output = Option<NodeEntity>;
    type Error = Error;
    #[tracing::instrument(name = "Query:FindNodeById", skip_all, err)]
    async fn process(&self, input: FindNodeById) -> Result<Self::Output, Self::Error> {
        let mut conn = self.db().acquire().await?;
        node_by_id(&mut conn, &input.id).await
    }
}

#[derive(Debug)]
pub struct FindNodeWithPorts {
    pub id: NodeId,
}

impl Processor<FindNodeWithPorts> for Db {
    type Output = Option<NodeWithPorts>;
    type Error = Error;
    #[tracing::instrument(name = "Query:FindNodeWithPorts", skip_all, err)]
    async fn process(&self, input: FindNodeWithPorts) -> Result<Self::Output, Self::Error> {
        let mut conn = self.db().acquire().await?;
        let Some(node) = node_by_id(&mut conn, &input.id).await? else {
            return Ok(None);
        };
        let ports = ports_of(&mut conn, &node.id).await?;
        Ok(Some(NodeWithPorts { node, ports }))
    }
}

/// The node importing `canvas`, if any.
#[derive(Debug)]
pub struct FindImporterOf {
    pub canvas: CanvasId,
}

impl Processor<FindImporterOf> for Db {
    type Output = Option<NodeEntity>;
    type Error = Error;
    #[tracing::instrument(name = "Query:FindImporterOf", skip_all, err)]
    async fn process(&self, input: FindImporterOf) -> Result<Self::Output, Self::Error> {
        let row: Option<NodeRow> =
            sqlx::query_as("SELECT * FROM orchestration_node WHERE import_canvas = $1")
                .bind(input.canvas)
                .fetch_optional(self.db())
                .await?;
        Ok(row.map(NodeEntity::from))
    }
}

/// Updates a node's editable metadata.
///
/// `position` is only written when it is `Some`, so an edit that leaves the
/// position out does not move the node. Whether the edit renamed the node is
/// decided inside the transaction, which is also where the canvas generation is
/// bumped, so a concurrent metadata write cannot land a rename without it.
pub struct UpdateNodeMetaRow {
    pub id: NodeId,
    pub canvas: CanvasId,
    pub name: String,
    pub comment: String,
    pub position: Option<CanvasUiPosition>,
    pub import_sync: Option<ImportSync>,
    /// The snapshot an export Y-move's `import_sync` was computed from; fences
    /// the mirrored-port reshape so a concurrent export edit is not erased by a
    /// stale list. `None` for renames/moves that carry no reshape.
    pub fence: Option<CanvasFence>,
}

/// A node after a metadata update, plus whether the name actually changed.
#[derive(Debug, Clone)]
pub struct NodeMetaUpdated {
    pub renamed: bool,
    pub node: NodeEntity,
    pub ports: Vec<PortEntity>,
}

impl Processor<UpdateNodeMetaRow> for Db {
    type Output = NodeMetaUpdated;
    type Error = Error;
    #[tracing::instrument(name = "Query-Transaction:UpdateNodeMetaRow", skip_all, err, fields(id = %input.id))]
    async fn process(&self, input: UpdateNodeMetaRow) -> Result<Self::Output, Self::Error> {
        // The node name is the forwarding tag in the derived worker config, so a
        // rename has to schedule a derivation; a move or a comment edit is
        // invisible to workers and leaves the generation alone. The old name is
        // read under a row lock inside this transaction rather than by the
        // caller, so a metadata write that started before a concurrent rename
        // cannot overwrite that rename without bumping.
        let mut tx = self.db().begin().await?;
        let previous: String =
            sqlx::query_scalar("SELECT name FROM orchestration_node WHERE id = $1 FOR UPDATE")
                .bind(&input.id)
                .fetch_one(&mut *tx)
                .await?;
        let renamed = previous != input.name;
        sqlx::query("UPDATE orchestration_node SET name = $2, comment = $3 WHERE id = $1")
            .bind(&input.id)
            .bind(&input.name)
            .bind(&input.comment)
            .execute(&mut *tx)
            .await?;
        if let Some(position) = input.position {
            sqlx::query(
                "UPDATE orchestration_node SET position_x = $2, position_y = $3 WHERE id = $1",
            )
            .bind(&input.id)
            .bind(position.x)
            .bind(position.y)
            .execute(&mut *tx)
            .await?;
        }
        // Moving an export node on the y axis renumbers the mirrored ports on the
        // node importing its canvas; that is a UI-only change too, but the list
        // was computed from a snapshot, so it is fenced: a concurrent export
        // edit that added a mirrored port cannot be erased by a stale list.
        if let Some(sync) = &input.import_sync {
            reshape_ports(&mut tx, &sync.node, &sync.ports).await?;
            fence::touch_checked(&mut tx, &input.canvas, input.fence.as_ref()).await?;
        } else if renamed {
            fence::touch(&mut tx, &input.canvas).await?;
        }
        let node = node_by_id(&mut tx, &input.id)
            .await?
            .ok_or(Error::Query(sqlx::Error::RowNotFound))?;
        let ports = ports_of(&mut tx, &input.id).await?;
        tx.commit().await?;
        Ok(NodeMetaUpdated {
            renamed,
            node,
            ports,
        })
    }
}

/// Rewrites a node's spec and reshapes its ports in place.
///
/// A port whose key survives keeps its row id, so the edges attached to it stay
/// attached; ports whose key disappears are deleted with their edges (the service
/// refuses the edit before that can happen silently).
pub struct UpdateNodeSpecRow {
    pub id: NodeId,
    pub canvas: CanvasId,
    pub spec: NodeSpec,
    pub ports: Vec<NewPort>,
    pub import_sync: Option<ImportSync>,
    /// The snapshot the edit was validated against, fencing the write.
    pub fence: Option<CanvasFence>,
}

impl Processor<UpdateNodeSpecRow> for Db {
    type Output = NodeWithPorts;
    type Error = Error;
    #[tracing::instrument(name = "Query-Transaction:UpdateNodeSpecRow", skip_all, err, fields(id = %input.id))]
    async fn process(&self, input: UpdateNodeSpecRow) -> Result<Self::Output, Self::Error> {
        let mut tx = self.db().begin().await?;
        write_spec(&mut tx, &input.id, &input.spec).await?;
        reshape_ports(&mut tx, &input.id, &input.ports).await?;
        if let Some(sync) = &input.import_sync {
            reshape_ports(&mut tx, &sync.node, &sync.ports).await?;
        }
        fence::touch_checked(&mut tx, &input.canvas, input.fence.as_ref()).await?;
        let node = node_by_id(&mut tx, &input.id)
            .await?
            .ok_or(Error::Query(sqlx::Error::RowNotFound))?;
        let ports = ports_of(&mut tx, &input.id).await?;
        tx.commit().await?;
        Ok(NodeWithPorts { node, ports })
    }
}

#[derive(Debug)]
pub struct DeleteNodeRow {
    pub id: NodeId,
    pub canvas: CanvasId,
    pub import_sync: Option<ImportSync>,
    /// The canvas this node stops importing (set when it is an import node): it
    /// becomes a root again and gets its own generation bump.
    pub frees_canvas: Option<CanvasId>,
    /// The snapshot the delete was validated against; `None` bumps
    /// unconditionally (an Admin force delete).
    pub fence: Option<CanvasFence>,
}

impl Processor<DeleteNodeRow> for Db {
    type Output = ();
    type Error = Error;
    #[tracing::instrument(name = "Query-Transaction:DeleteNodeRow", skip_all, err)]
    async fn process(&self, input: DeleteNodeRow) -> Result<Self::Output, Self::Error> {
        let mut tx = self.db().begin().await?;
        // Ports, their edges, the node's health history and its relay leaf all
        // cascade from the row.
        sqlx::query("DELETE FROM orchestration_node WHERE id = $1")
            .bind(&input.id)
            .execute(&mut *tx)
            .await?;
        // Retiring an export node drops its mirrored port (and that port's edge)
        // on the importing node.
        if let Some(sync) = &input.import_sync {
            reshape_ports(&mut tx, &sync.node, &sync.ports).await?;
        }
        fence::touch_checked(&mut tx, &input.canvas, input.fence.as_ref()).await?;
        // Retiring an import node makes its target a root again, with a
        // derivation pass of its own to run.
        if let Some(freed) = &input.frees_canvas {
            sqlx::query(
                "UPDATE orchestration_canvas SET generation = generation + 1 WHERE id = $1",
            )
            .bind(freed)
            .execute(&mut *tx)
            .await?;
        }
        tx.commit().await?;
        Ok(())
    }
}

/// The distinct canvases the given nodes belong to; the relay leaf rotation
/// cron re-derives these after re-issuing.
#[derive(Debug)]
pub struct ListCanvasesOfNodes {
    pub nodes: Vec<NodeId>,
}

impl Processor<ListCanvasesOfNodes> for Db {
    type Output = Vec<CanvasId>;
    type Error = Error;
    #[tracing::instrument(name = "Query:ListCanvasesOfNodes", skip_all, err)]
    async fn process(&self, input: ListCanvasesOfNodes) -> Result<Self::Output, Self::Error> {
        if input.nodes.is_empty() {
            return Ok(Vec::new());
        }
        Ok(sqlx::query_scalar(
            "SELECT DISTINCT canvas FROM orchestration_node WHERE id = ANY($1) ORDER BY canvas",
        )
        .bind(&input.nodes)
        .fetch_all(self.db())
        .await?)
    }
}

/// The root canvases of every tree holding a TLS or QUIC relay: the trees whose
/// derivation depends on the internal CA. `InitInternalCa` touches them so pods
/// reported invalid for lack of a CA get their first leaves.
#[derive(Debug)]
pub struct ListCanvasesWithRelayTls;

impl Processor<ListCanvasesWithRelayTls> for Db {
    type Output = Vec<CanvasId>;
    type Error = Error;
    #[tracing::instrument(name = "Query:ListCanvasesWithRelayTls", skip_all, err)]
    async fn process(&self, _: ListCanvasesWithRelayTls) -> Result<Self::Output, Self::Error> {
        let mut conn = self.db().acquire().await?;
        let canvases: Vec<CanvasId> = sqlx::query_scalar(
            "SELECT DISTINCT canvas FROM orchestration_node
             WHERE spec ->> 'type' = 'relay'
               AND spec -> 'config' ->> 'protocol' IN ('tcp_tls', 'quic')",
        )
        .fetch_all(&mut *conn)
        .await?;
        let mut roots = Vec::with_capacity(canvases.len());
        for canvas in &canvases {
            roots.push(tree::root_of(&mut conn, canvas).await?);
        }
        roots.sort();
        roots.dedup();
        Ok(roots)
    }
}
