UPDATE orchestration_server
SET name = $2, icon = $3, comment = $4, ipv6_resolve = $5, log_level = $6,
    override_v4 = $7, override_v6 = $8, extra_addresses = $9, agent_unit = $10,
    quic = $11
WHERE id = $1
RETURNING id AS "id: ServerId",
          canvas AS "canvas: CanvasId",
          name,
          icon,
          comment,
          position_x,
          position_y,
          ipv6_resolve AS "ipv6_resolve: ServerIpv6Resolve",
          log_level AS "log_level: ServerLogLevel",
          quic AS "quic: Json<ServerQuic>",
          current_dynamic_refresh_key,
          refresh_key_generation,
          watch_epoch,
          session_lease_until,
          registered_at,
          last_seen_at,
          last_health_report_at,
          health_status AS "health_status: ServerHealthStatus",
          override_v4,
          override_v6,
          extra_addresses,
          reported_addresses AS "reported_addresses: Json<ReportedAddresses>",
          observed_address,
          observed_at,
          agent_version,
          agent_arch,
          agent_unit,
          agent_update_requested,
          agent_update_error,
          agent_key_digest,
          agent_key_issued_at,
          country,
          country_address,
          country_checked_at,
          capabilities
