[package]
name = "auth"
version = "0.1.0-alpha"  # master side
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
# Internal
rpguru_sdk = { path = "../../lib/rpguru_sdk" }

# Framework
wakuwaku = { workspace = true }
kanau = { workspace = true }
tokio = { workspace = true }

# Persistence
newtype_record_id = { path = "../../lib/newtype_record_id" }
surrealdb = { workspace = true }
surrealdb-types = { workspace = true }

# gRPC / transport
tonic = { workspace = true }

# Serialization
serde = { workspace = true }

# Data types
chrono = { workspace = true }

# Tracing
tracing = { workspace = true }

# Error handling
anyhow = { workspace = true }
thiserror = { workspace = true }

# Auth & Security
argon2 = { workspace = true }
rand = { workspace = true }
sha2 = { workspace = true }

# gRPC transport middleware
tower = { workspace = true }

[dev-dependencies]
surrealdb = { workspace = true, features = ["kv-mem"] }
