[package]
name = "guru_topology"
version = "1.0.0"  # master side
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
guru_worker_config = { path = "../guru_worker_config" }
serde = { workspace = true }
smallvec = { workspace = true }

[dev-dependencies]
serde_json = { workspace = true }
