[package]
name = "guru_worker_config"
version = "0.3.4-beta"  # worker side
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { version = "1", features = ["derive"] }
compact_str = { workspace = true }
smallvec = { version = "1.15", features = [
    "serde",
    "union",
    "const_generics",
    "const_new",
] }
toml = "1"
thiserror = { workspace = true }
